[package]
name = "spipe"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "spipe"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.102", features = ["extra-traits"] }

[dev-dependencies]
prettyplease = "0.2.33"
